config/routes.rb
Rails.application.routes.draw do



 get '/users/trade' => 'users#trade'



  get 'trades/findcompany', to: "trades#findcompany"
  get 'users/newtrade', to: "users#newtrade"
  resources :examples
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { sessions: "devise/sessions", omniauth_callbacks: 'omniauth_callbacks' }
  get 'auth/:provider/callback', to: 'devise/sessions#create'


  get '/', to: "staticpages#home"
  get '/leaderboard', to: "staticpages#leaderboard"
  post 'search' => 'users#search'

  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  root 'devise/sessions#new'
  end


  resources :companies do
    collection do
      get 'events'
    end
  end

  # post 'companies/publish', to: "companies#pub"
  #
  # get 'companies/subscribe', to: "companies#sub"



  get 'staticpages/help'

  get 'staticpages/tour'
  get 'staticpages/about'
  get 'staticpages/rank'

  get 'static/pages'
  get 'users/preview'
  get 'users/revise'
  get 'staticpages/news/:id', to: "staticpages#news"
  get 'usearch/:name', to: "staticpages#usearch"
  # get '/sectors/:id', to: "sectors#show"
  resources :sectors

  resources :users do
    resources :trades
  end





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable


  scope :online, -> { where("updated_at > ?", 10.minutes.ago) }
  has_many :trades
  accepts_nested_attributes_for :trades
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lastseenable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "30x30!"}, default_url: "/images/:style/missing.png"

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.provider = auth.provider
    user.uid = auth.uid
    user.password = Devise.friendly_token[0,20]
    user.token = auth.credentials.token
    user.expires = auth.credentials.expires
    user.expires_at = auth.credentials.expires_at
    user.refresh_token = auth.credentials.refresh_token




   end
  end


  def totalprof
    self.longprofit = self.trades.where(tradetype: "Long").sum(:currentprice) - self.trades.where(tradetype: "Long").sum(:stockprice)
    self.shortprofit = self.trades.where(tradetype: "Short").sum(:stockprice) - self.trades.where(tradetype: "Short").sum(:currentprice)
    self.commprofit = self.trades.where.not(commodity_id: nil).sum(:currentprice) - self.trades.where.not(commodity_id: nil).sum(:stockprice)
     self.totalprofit =   self.longprofit + self.shortprofit + self.commprofit
     self.save
  end

  def self.online_now
      where("last_seen > ?", 15.minutes.ago)
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]
  require 'openssl'
  require 'open-uri'
  require 'restclient'



  def index
    @users = User.all
  end
  def trade
    # current_user
  end
  # def newtrade
  #   # name = params[:name]
  #   # tick = params[:tick]
  #   # vol = params[:vol]
  #   # price = params[:price]
  #   # total = params[:total]
  #   @trade = Trade.find(2)
  #   name = "some thing"
  #   tick = "AARL"
  #   vol = 23
  #   price = 201.10
  #   total = 4029.90
  #   # if Trade.where(ticker: params[:tick])
  #   #   # dont create trade
  #   #   @trade = Trade.where(ticker: params[:tick])
  #   # else
  #     # @trade1 = Trade.create(stock: name,
  #     # ticker: tick,
  #     # tradeprice: total,
  #     # volume: vol,
  #     # stockprice: price)
  #
  #     # @currentuser.wallet = @currentuser.wallet - @trade.tradeprice
  #   # end
  # end
  def newtrade
    # @this = "this"
    # @this = Trade.find(2)

#
  # name = "Apple Inc. - Common Stock"
  # tick = "AAPL"
  # vol = 90
  # price = 243.42
  # total = 22320
  # type = "Sell"
  name = params[:name]
  tick = params[:tick]
  vol = params[:vol].to_i
  price = params[:price].to_f
  total = params[:total].to_f
  type = params[:type]
  tc = "Trade Complete"
    if type == "Buy" # IF ONE START 11111111111111

      @currentuser = current_user
      w = @currentuser.wallet
        if Trade.where(ticker: params[:tick]).exists?
          if w > total
            @trade = Trade.where(ticker: params[:tick]).first
            @trade.volume += vol
            @trade.save
            @currentuser.wallet -=  total
            @currentuser.save
            @text = tc
          elsif w < total
            @text = "You do not have enough units to make this trade."
          end
        else  #graduate to using first_or_create
          @trade = @currentuser.trades.create(stock: name,
           ticker: tick,
           tradeprice: total,
           volume: vol,
           stockprice: price)
          @currentuser.wallet -=  total
          @currentuser.save
          @text = tc
        end
    else   # ELSE ONE START 11111111111111
      @currentuser = current_user
      w = @currentuser.wallet
     if Trade.where(ticker: params[:tick]).exists?  # IF TWO START 222222222222
       if Trade.where(ticker: params[:tick]).first.volume >= vol
         @trade = Trade.where(ticker: params[:tick]).first
         @trade.volume -= vol
         @trade.save
         @currentuser.wallet +=  total
         @currentuser.save
         @text = tc
      else
        @text = "You do not have enough shares to make this trade."
      end
    else   # ElSE TWO START 222222222222
       @text = "Could not complete trade. You do not have enough shares in this company."
     end  # IF TWO END 222222222222
   end # IF ONE END 11111111111111


    end # end of method



  def showtrade
    #here i will get the company from ticker
    #to show you current price in that orange
  end

  # GET /users/1
  # GET /users/1.json
  def show

    @user = User.find(params[:id])
    @trades = @user.trades.all
    if current_user.id == params[:id].to_i
      @iscurrentuser = true
    else
      @iscurrentuser = false
    end
    @idcurr = current_user.id
    @par = params[:id]
    @gain = @user.wallet - 10000
    @gainpercent = (@user.wallet.to_f / 100.0) - 100.0
    @us = User.order('wallet DESC').pluck(:id).index(@user.id)
    Trade.highall
    @order = @trades.order('change DESC')
    @high = 0  # @order.first.change * 100  ADD MORE TRADES THEN UNCOMMENT
    @low = 0    #@order.last.change * 100
    sumarr = []
    @trades.each do |t|
      sum = t.currentprice * t.volume.to_f
      sumarr << sum
    end
    @tp = (@user.wallet + sumarr.sum) - 10000.0
    @held =  @trades.where.not(volume: 0).order('created_at DESC')
    if @held.first && @held.last
      @oldest = @held.first.ticker
      @newest = @held.last.ticker
    end
    # @trade = Trade.new
    # @test = Company.search(params[:search]).paginate(page: params[:page], per_page: 30)
    # @reg = Region.all
    # @exch = Exchange.all
    # @comp = Company.all + Commodity.all
    # @camp = Company.all.pluck(:currentprice)
    # @comm = Commodity.all.pluck(:id)  #trade the first one   make sure its right

    # @nokocomp = Company.first
    # @nokocomp.noko
    # @nokocomp.noko2
    # @nokocomp.noko3
    # @nokocomp.noko4
    # @nokocomp.noko5
    # @nokocomp.noko6
    #  @trades = Trade.where(nil) # creates an anonymous scope
    #  @trades = @trades.region_id(params[:region_id]) if params[:region_id].present?
    #  @tradelongs = @trades.where(tradetype: "Long")
    #  @tradeshorts = @trades.where(tradetype: "Short")
    #  # @trade = Trade.where(user_id: params[:id])
    #  # @trade.first.tradeprices   #going to do this for all
    #  # @trade.first.tradeset
     # @alltrades = Trade.where.not(volume: nil, stockprice: nil)
     # @alltrades.each do |t|
     #   t.tradeprices
     #  end
     # @comptrade = @trade.first      #we're talking about trade 2
     # @bigcomp = @test.order('changepercent DESC').limit(20)
     # respond_to do |format|
     #   format.js
     #   format.html
     # end

   end

   def show_online
     @users = User.online_now
   end
  # GET /users/new  going back to the first one i think so
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    userip = request.remote_ip
    results = Geocoder.search(userip)
    @user.country = results.first.country


    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      elsif params[:preview_button]
        format.html { render :new }
      elsif !@user.save
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user     # @trade = Trade.where(user_id: params[:id])
    @user.update(user_params)

    #im going to set one to two from here
    # respond_to do |format|
    #   if @user.update(user_params)
    #     format.html { redirect_to :action => "show", :controller => "trades"}
    #     format.json { render :show, status: :ok, location: @user }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @user.errors, status: :unprocessable_entity }
    #   end
    # end
  end
  def revise
    #delete it here
    @user = User.order(:updated_at).last
    @user.trades.last.destroy
    @user.save               #at this point it updates user
    redirect_back fallback_location: { action: "show", id: 18 }
  end

  def search
    begin

   @user = User.find_by_name params[:name]
   @alltrades = Trade.where.not(volume: nil, stockprice: nil)

   @trade = Trade.new
   @reg = Region.all
   @exch = Exchange.all
   @comp = Company.all + Commodity.all
   @camp = Company.all.pluck(:currentprice)
   @comm = Commodity.all.pluck(:id)  #trade the first one   make sure its right

   @nokocomp = Company.first
   @nokocomp.noko
   @nokocomp.noko2
   @nokocomp.noko3
   @nokocomp.noko4
   @nokocomp.noko5
   @nokocomp.noko6
    @trades = Trade.where(nil) # creates an anonymous scope
    @trades = @trades.region_id(params[:region_id]) if params[:region_id].present?
    @tradelongs = @trades.where(tradetype: "Long")
    @tradeshorts = @trades.where(tradetype: "Short")

      render action: 'show'
    rescue StandardError
     redirect_to "/admin"

      raise
     end

  end
  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def preview
       @test = Company.search(params[:searched])
  end


    # Use callbacks to share common setup or constraints between actions.

    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:id, :email, :avatar, :password, trades_attributes: [:id, :stock, :volume, :user_id, :region_id, :tradetype, :stockprice, :one, :company_id, :commodity_id])
    # dont vhange this or server will stall
    end
 end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= form.file_field :avatar %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_leaderboard.html.erb
<table class="tbl" border="1">
    <th>No</th> <th>Name</th><th>ranking</th>
  <% User.order("totalprofit Desc").each do |u| %>

    <tr>
        <td></td> <td><%= u.name %></td><td><%= u.totalprofit %></td>
    </tr>

    <% end %>
</table>

app/views/users/_table.html.erb
<div class="wrapmid">

  <div class="recenttrades">
     <div class="cardheader">Recent Trades <span class="track">live tracker</span></div>
     <% @user.trades.order("created_at").last(3).each do |t| %>
     <ul class="result">
       <li><span class="lss"><%= t.tradetype %></span><br><span class="title"><%= t.created_at%></span></li>
       <li>Stock <br><%= t.stock %></li>
       <li>Volume <br><%= t.volume %></li>
       <li>Price <br><%= t.stockprice %></li>
     </ul>
     <% end %>
 </div>







  <ul class="longsover">
     <li class="onee"><div class="longover">Longs</div><div class="longsval"># <%= @tradelongs.count %></div></li>
     <li><div class="rateover">Rating</div><div class="ratingval"># </div></li>
     <li><div class="profitover">Profit</div><div class="profitval"><%= @user.trades.where(tradetype: "Long").sum(:currentprice) - @user.trades.where(tradetype: "Long").sum(:stockprice)%></div></li>
     <li><div class="percentover">Percent Long</div><div class="percentval"> <% price = (@user.trades.where(tradetype: "Long").count.to_f / @user.trades.count.to_f) * 100  %><%= number_with_precision(price, :precision => 0) %>%</div></li>
     <li><div class="numover">Stocks Long</div><div class="numval"><%= @user.trades.where(tradetype: "Long").count %></div></li>
  </ul>
  <ul class="longsover">
      <li class="onee"><div class="longover">Short</div><div class="longsval"># <%= @tradeshorts.count %></div></li>
      <li><div class="rateover">Rating</div><div class="ratingval">#</div></li>
      <li><div class="profitover">Profit</div><div class="profitval"><%= @user.trades.where(tradetype: "Short").sum(:stockprice) - @user.trades.where(tradetype: "Short").sum(:currentprice) %></div></li>
      <li><div class="percentover">Percent Short</div><div class="percentval"><% shrtprice = (@user.trades.where(tradetype: "Short").count.to_f / @user.trades.count.to_f) * 100  %><%= number_with_precision(shrtprice, :precision => 0) %>%</div></li>
      <li><div class="numover">Stocks Short</div><div class="numval"><%= @user.trades.where(tradetype: "Short").count %></div></li>
  </ul>
  <ul class="longsover">
        <li class="onee"><div class="longover">Other Comm.</div><div class="longsval">#</div></li>
        <li><div class="rateover">Rating</div><div class="ratingval">#</div></li>
        <li><div class="profitover">Profit</div><div class="profitval"><%= @user.trades.where.not(commodity_id: nil).sum(:currentprice) - @user.trades.where.not(commodity_id: nil).sum(:stockprice)%></div></li>
        <li><div class="percentover">Percent in Commodities</div><div class="percentval"><% price = (@user.trades.where.not(commodity_id: nil).count.to_f / @user.trades.count.to_f) * 100  %><%= number_with_precision(price, :precision => 0)%>%</div></li>
        <li><div class="numover">Commodities</div><div class="numval"><%= @user.trades.where.not(commodity_id: nil).count%></div></li>

  </ul>





                  <div class="careerstats">Career Stats
                    <ul class="careertrades">
                      <li>Trades Made <br> <%= @user.trades.count('stock') %> </li>
                    <%  @something = [ ] %>
                     <% @user.trades.where.not(currentprice: nil).each do |f| %>
                      <%  if f.stockprice != nil && f.stockprice > f.currentprice %>
                    <%  @something << f %>
                    <%  end %>
                     <% end %>
                      <li>Currently Up <%= @something.count %></li>
                      <%  @somethingminus = [ ] %>
                       <% @user.trades.where.not(currentprice: nil).each do |f| %>
                        <%  if f.stockprice != nil && f.stockprice < f.currentprice %>
                      <%  @somethingminus << f %>
                      <%  end %>
                       <% end %>
                      <li>Currently Down <%= @somethingminus.count %></li>
                    </ul>
                    <ul class="careertrades">
                      <li>Companies Held <%= @user.trades.distinct.count('stock') %></li>

                      <li>Profit  <%= @user.trades.sum(:stockprice) - @user.trades.sum(:currentprice) %></li>
                    </ul>
                  </div>


                  <div class="orangetrending">
                 <%= @idcurr %> <br>
                 <%= @iscurrentuser %> <br>
                 <%= @par %>
                </div>







    </div>

app/views/users/_thestage.html.erb
<% @user.trades.find(30) do |t| %>
<%= t.stockprice * t.volume %>
<% end  %>

app/views/users/_thetrade.html.erb
  <div class="tradecomp">
  <div id="companies_searchw" action="http://localhost:3000/users/3" accept-charset="UTF-8" method="get">
  <div class="csearch">
     <%= text_field_tag :search, nil, placeholder: "Search Companies...", id: "isearch" %>
   </div>
   </div>
<div class="myTrade">
</div>
<br>

<%= select_tag(:type, options_for_select([ "Sell", "Buy" ], "Buy"), {class: 'buysl'}) %><br>
<br>
<div>Volume: <%= number_field_tag 'quantity', id: "ivolume" %>
<br>
<br>
<div>Share Price: <%= number_field_tag 'iprice', disabled: true %></div>
<br>
<br>
<div>Total $: <%= number_field_tag 'total', disabled: true %></div>
<br>
<br>
<div class="mTrade"></div>


  </div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<%=  @user %>
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>

      <tr>
        <td><%= user.email %><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/newtrade.html.erb
<div class="info"><%= @text %></div>
<div class="info"><%= "  Balance: #{@currentuser.wallet}" %></div>

app/views/users/preview.html.erb
  <table class="lmyTable">
    <tr>
      <th>Symbol</th>
      <th>Name</th>
    </tr>
    <div class="rmplc"><% @test.limit(10).each do |c| %>
    <tr class="tap">
      <td class="pvtick"><%= link_to c.ticker, "https://www.nasdaq.com/symbol/#{c.ticker}" %></td>
      <td class="pvctitle"><%= c.otherdata %></td>
    </tr>
  <% end %>
  </div>
  </table>

app/views/users/show.html.erb
<div class="usercontainer">
<div class="homenav">
<div class="offset">
<div class="centerset">
  <div class="topset">
  <div class="logo">
      <%= link_to "SportFolio", root_path, id: "homelogo" %>
  </div>
  <div class="searchhold">
     <div class="inputsm">
       <div class="refSearch"><i class="fa fa-search"></i></div>
       <input type="text" id="inputTxt" placeholder="Search">
     </div>
  </div>
  <div class="signup">
          <% if user_signed_in? %>
          <%= link_to "Edit profile", edit_user_registration_path %> |
          <%= link_to "Logout", users_sign_out_path, method: :delete  %>
          <% else %>
          <i class="fab fa-facebook-f"></i>
           <i class="fas fa-user"></i><%= link_to "Sign up", new_user_registration_path  %> |
           <%= link_to "Login", new_user_session_path  %>
          <% end %>
  </div>
  </div> <!-- topset -->
  <div class="bottomset">

    <ul class="setlist">
      <li><%= link_to "COMPANIES", companies_path%></li>
      <li>NEWS</li>
      <li><%= link_to "LEADERBOARD", leaderboard_path%></li>
      <% if user_signed_in? %>
      <li><%= link_to "PROFILE", user_path(current_user)%></li>
      <li>GO PREMIUM</li>

      <% else %>
      <li><%= link_to "HOME", root_path %></li>
      <li>GO PREMIUM</li>

      <% end %>
    </ul>
  </div>
  </div>  <!-- centerset -->
</div>
</div>   <!-- homenav -->
<div  class="offsetsmpro">
  <div class="userboxtop">
    <div class="userboxtopha">
      <div class="tolo uname"><%= @user.name %></div>
     <div class="tolo"><%= "United States" %> </div>
     <div class="toro"><%= "Last Online: #{@user.last_seen}" %></div>
    </div>
  </div>

  <div class="userboxle">
    <div class="lifetimetop">
      <div class="lifetimetab">
        <span class="lifetimetabsp">LIFETIME</span>

        </div>
      </div>

    <div class="lifetimelast">
      <div class="ltlast">
        <i class="fas fa-history"></i>
        <span id="lastbold">Last 3 Trades:
      </div>
      <% @trades.last(3).each do |t| %>
      <div class="ltrest">
        <div class="datetop">
          <span class="datm"><%= t.updated_at.strftime("%m/%d/%Y") %></span>
        </div>
        <div class="ticktop">
          <%= t.ticker %>
        </div>
      </div>
      <% end %>
    </div> <!-- lifetimelast -->
    <div class="lifetimemain">
      <div class="mainstat">
        <div class="mainstattop">
          TOTAL UNITS
        </div>
        <div class="mainstatbottom">
          <%= @user.wallet %>
        </div>
      </div>
      <div class="mainstat">
        <div class="mainstattop">
          COMPANIES HELD
        </div>
        <div class="mainstatbottom"><%= @user.trades.count %></div>
      </div>
      <div class="mainstat">
        <div class="mainstattop">
             OVERALL GAIN/LOSS
        </div>
        <div class="mainstatbottom">
          <%= @gain %>
        </div>
      </div>
      <div class="mainstat">
        <div class="mainstattop">
            GAIN PERCENT
        </div>
        <div class="mainstatbottom">
          <%= "#{@gainpercent}%" %>
        </div>
      </div>
    </div>
  </div>


  <div class="userboxlow">

    <div class="uboxlowtop">
      <span>OVERVIEW</span>
    </div>
    <div class="uboxlowmid">

    <div class="uboxlow">
      <span class="uboxtitle"><%= Title.find(1).text %></span>
      <div class="uboxvalue"><%= @us %></div>
    </div>
    <div class="uboxlow">
      <span class="uboxtitle"><%= Title.find(2).text %></span>
      <div class="uboxvalue"><%= @user.country %></div>
    </div>
    <div class="uboxlow">
      <span class="uboxtitle"><%= Title.find(3).text %></span>
      <div class="uboxvalue"><%= @user.tradecount %></div>
    </div>
    <div class="uboxlow">
      <span class="uboxtitle"><%= Title.find(4).text %></span>
      <div class="uboxvalue"><%= @high %></div>
    </div>
    <div class="uboxlow">
      <span class="uboxtitle"><%= Title.find(5).text %></span>
      <div class="uboxvalue"><%= @low %></div>
    </div>
    <div class="uboxlow">
      <span class="uboxtitle"><%= Title.find(6).text %></span>
      <div class="uboxvalue"><%= @tp %></div>
    </div>
    <div class="uboxlow">
      <span class="uboxtitle"><%= Title.find(7).text %></span>
      <div class="uboxvalue"><%= @oldest %></div>
    </div>
    <div class="uboxlow">
      <span class="uboxtitle"><%= Title.find(8).text %></span>
      <div class="uboxvalue"><%= @newest %></div>
    </div>
    <div class="uboxlow">
      <span class="uboxtitle"><%= Title.find(9).text %></span>
      <div class="uboxvalue"><%= @user.created_at.strftime("%m/%d/%Y") %></div>
    </div>

    </div>
  </div><!-- userboxlow -->
  <div class="viewall">
    <div class="viewallbar"><div class="rtrade">RECENT TRADES</div></div>
    <div class="tmv">
       <div class="viewallrecboxupper ">Company</div>
       <div class="viewallrecboxupper">Type</div>
       <div class="viewallrecboxupper">Created  </div>
       <div class="viewallrecboxupper vbr">Volume</div>
       <div class="viewallrecboxupper vbr">Price</div>
    </div>
    <% @trades.limit(10).each do |t| %>
    <div class="viewallrec">
       <div class="viewallrecbox vbb"><%= t.ticker %></div>
       <div class="viewallrecbox whh"><%# t.type %></div>
       <div class="viewallrecbox whh"><%= "#{time_ago_in_words(t.created_at)} ago"%></div>
       <div class="viewallrecbox vbr whh"><%= t.volume %></div>
       <div class="viewallrecbox vbrg"><%= t.currentprice %></div>
    </div>
    <% end %>
  </div>





 </div>  <!-- offsetsm -->


<div class="tradelate">

</div>


</div>  <!-- containerss -->





<div class="spc">
</div>


  <script>
   let functionIsRunning = false;
   let companyTick;
      $(document).on("keyup", "#companies_searchw input", function() {
          searchtxt = $("#companies_searchw input").val();
          if (functionIsRunning == false) {
          functionIsRunning = true;
        $.ajax({
            type: "GET",
            url: "http://localhost:3000/users/preview",
            data: { searched: searchtxt},
            success: function(response) {

                result = $(response).find(".lmyTable");
                $(".myTrade").empty().append(response);

                $(".tap").click(function(){
                  let companyTick = $( this ).find( ".pvtick" ).text()
                   companyName = $( this ).find( ".pvctitle" ).text()
                   console.log(companyTick)

                  $("#companies_searchw input").val(companyName);
                  $(".myTrade").empty();
                  $.ajax({
                      url: "http://localhost:3000/trades/findcompany",
                      data: {company: companyTick},// all attributes of created and type createorbyorsell},
                      success: function(response){ // put a set timeout and give time to load
                        setTimeout(function(){
                          price = $( response ).filter("#msm")
                        $("#iprice").val($(price).text())
                        console.log($(price))
                      }, 500) //end of setTimeout

                      $(".makeTrade").click(
                      function() {
                        //before we get all attribute  inputs
                        //we need to find thr company based on name  // currentprice of company
                        //  don't allow user to surpass wallet -- send a red notification

                         company = $("#isearch").val()
                         vol = $('#quantity').val()
                         price = $("#iprice").val();
                         total = $("#total").val();
                         console.log("tick: " + companyTick)
                         console.log("company: " + company)
                         console.log("vol: " + vol)
                         console.log("p: " + price)
                         console.log("total: " + total)
                      $.ajax({
                          url: "http://localhost:3000/users/newtrade",
                          data: {name: company, vol: vol, price: price, total: total, tick: companyTick },// all attributes of created and type createorbyorsell},
                          success: function(response){
                            info = $(response).filter(".info")
                            //send notification of worked or did not work
                            // it controller it either saves or doesn't saved   // due to cost
                           $('.orangetrending').empty().append($(info).text())
                        }
                       });
                      }
                      ); //end of maketrade



                    } // end of ajax
                  })
                }) //end of pvctitle click

              }// end of success

            }); //end of ajax
            functionIsRunning = false
          } //end of if

          }); //end of document keyup

          $( "#quantity" ).keyup(function() {
          num = $(this).val();
          price = $("#iprice").val();
          p = parseInt(price);
          total = num * p;
          $("#total").val(total) ;
          console.log(total, num, p)
        })
//on submit

    </script>