config/routes.rb
Rails.application.routes.draw do



 get '/users/trade' => 'users#trade'



  get 'trades/findcompany', to: "trades#findcompany"
  get 'users/newtrade', to: "users#newtrade"
  resources :examples
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { sessions: "devise/sessions", omniauth_callbacks: 'omniauth_callbacks' }
  get 'auth/:provider/callback', to: 'devise/sessions#create'


  get '/', to: "staticpages#home"
  get '/leaderboard', to: "staticpages#leaderboard"
  post 'search' => 'users#search'

  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  root 'devise/sessions#new'
  end


  resources :companies do
    collection do
      get 'events'
    end
  end

  # post 'companies/publish', to: "companies#pub"
  #
  # get 'companies/subscribe', to: "companies#sub"



  get 'staticpages/help'

  get 'staticpages/tour'
  get 'staticpages/about'
  get 'staticpages/rank'

  get 'static/pages'
  get 'users/preview'
  get 'users/revise'
  get 'staticpages/news/:id', to: "staticpages#news"
  get 'usearch/:name', to: "staticpages#usearch"
  # get '/sectors/:id', to: "sectors#show"
  resources :sectors

  resources :users do
    resources :trades
  end





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
   skip_before_action :authenticate_user!
  rescue_from ActionView::Template::Error, with: :handle_timeout
  rescue_from Timeout::Error, with: :handle_timeout

  include ActionController::Live



  def index

  end
  def usearch
    if User.where(name: params[:name])
      @user = User.where(name: params[:name])
      redirect_to "https://sheltered-journey-51023.herokuapp.com/users/#{@user.first.id}"
      #redirect_to "http://localhost:3000/users/#{@user.first.id}"
    else
      flash[:notice] = 'Could not find user. Please try again. '
      redirect_to root_path
    end
  end
  def home
    News.save_data_from_api
    @companies = Company.all
    @bigcomp = @companies.order('changepercent DESC').limit(20)
    @company = Company.first
    # @company.delay.updatecurrentandvol
    # @company.delay.updatechanges
    @users = User.all
    @ranker = @users.order('wallet DESC').first
    @trader = @users.left_joins(:trades).group(:id).order('COUNT(trades.id) DESC').first
    @newest = @users.order('created_at DESC').first

    # @users.each do |u|
    #   u.totalprof
    # end

  end

  def help
    @companies = Company.all
  end
  def news
    @news = News.find(params[:id])
  end
  def rank
    n = params[:topnum]
    str = params[:topstr]


    User.order('wallet DESC').limit(n).each do |u|
      u.toprank = str
      u.save
    end
  end

  def leaderboard
    @users = User.order("totalprofit DESC").paginate(page: params[:page], per_page: 5)
    @numunrounded = User.count / 2
    @num = @numunrounded.round
    @total = User.count
    # @userspag = @users.limit(@num)   ?????
    # @offset = @users.offset(@num)
  end



  def about
    @test = Company.all
  end

  protected

  def handle_timeout(exception)
    count = 0
    begin
        raise if count > 5
      rescue
        count += 1
      retry

    end
  end

end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/staticpages/_scroll.html.erb
<div class="companies">
  <div class="wrapp">
  <div class="marquee">
    <div class="slide">
      <span class="spanner" data-url="<%= companies_url %>">


 <div>

 </div>


</span>
      </div>
  </div>
 </div>

</div>

app/views/staticpages/about.html.erb
 <% loop do %>
<% @test.find_each(batch_size: 10) do |c| %>
<%= c.checktwo %>
 <% c.save %>
 <% end %>
<% end %>

app/views/staticpages/help.html.erb
<p>some stuff</p>


<!-- test out api call with model method -->
 <!-- <% loop do %>
  <% @companies.find_each(batch_size: 10) do |c| %>
  <% c.checkthree %>
  <% c.save %>
  <% end %>
<% end %> -->

app/views/staticpages/home.html.erb
<div class="containerss">
<div class="homenav">
<div class="offset">
  <div class="centerset">
    <div class="topset">
  <div class="logo">
      <%= link_to "SportFolio", root_path, id: "homelogo" %>
  </div>
  <div class="searchhold">
     <div class="inputsm">
       <div class="refSearch"><i class="fa fa-search"></i></div>
       <input type="text" id="inputTxt" placeholder="Search">
     </div>
  </div>
  <div class="signup">

          <% if user_signed_in? %>
          <%= link_to "Edit profile", edit_user_registration_path %> |
          <%= link_to "Logout", users_sign_out_path %>
          <% else %>
          <i class="fab fa-facebook-f"></i>
           <i class="fas fa-user"></i><%= link_to "Sign up", new_user_registration_path  %> |
           <%= link_to "Login", new_user_session_path  %>
          <% end %>
  </div>



  </div> <!-- topset -->
  <div class="bottomset">

    <ul class="setlist">
      <li><%= link_to "COMPANIES", companies_path%></li>
      <li>NEWS</li>
      <li><%= link_to "LEADERBOARD", leaderboard_path%></li>
      <% if user_signed_in? %>
      <li><%= link_to "PROFILE", user_path(current_user)%></li>
      <li><%= link_to "CREATE TRADE", users_trade_path%></li>

      <% else %>
      <li><%= link_to "HOME", root_path %></li>
      <li>GO PREMIUM</li>

      <% end %>
    </ul>
  </div>
  </div>  <!-- centerset -->


</div>


</div>   <!-- homenav -->


<div  class="offsetsm">
<div class="containsm">
  <div class="tsm">ENTER USERNAME</div>
  <div class="csm"><input type="text" id="containTxt" placeholder="Enter a name"></div>
</div>




</div>  <!-- offsetsm -->

</div>  <!-- containerss -->
<div class="boxsetwrap">
  <div class="boxsetinner">
  <div class="boxset"><div class="rboxset ysb">Most Trades</div>
  <div class="ymidset"><%= image_tag @trader.avatar.url(:thumb) %> <%= @trader.name %></div>
 </div>
  <div class="boxset"><div class="gboxset ysb">Highest Rank</div>
  <div class="ymidset"><%= image_tag @ranker.avatar.url(:thumb) %> <%= @ranker.name %></div>
  </div>
  <div class="boxset"><div class="yboxset  ysb">Newest Member</div>
  <div class="ymidset"><%= image_tag @newest.avatar.url(:thumb) %> <%= @newest.name %></div>
  </div>
</div>
</div>
<div> nav info section </div>




<div class="lcontainer">
<div class="covcontainer">
<div class="newscontainer">
<%  News.all.limit(5).order("created_at DESC").each do |n| %>

<div class="newsbox">
  <%= image_tag "#{n.imageurl}", class: "nimg" %>
  <div class="extracont">
    <div class="extratitle">
    <%= n.title.titlecase %>
    </div>
    <div class="extrapub">
    <%= "Published on " + n.publishedon.strftime('%a, %d %b %Y') %>
    </div>
    <div class="extrabutton">
     <%= link_to "Read More", "staticpages/news/#{n.id}" %>
    </div>

  </div>
</div> <!--newsbox-->
<br>
<% end %>
</div> <!--newscontainer-->


<div class="leadandonline">
<div class="minileaderboard">
  <table>

    <tr>
      <th>#</th>
      <th>Trader</th>
      <th>Units</th>
    </tr>
    <% User.order("wallet DESC").each_with_index do |u, index|  %>
    <tr>
      <td><%= index + 1%></td>
      <td><span class="i"><%= image_tag u.avatar.url(:thumb) %></span><%= u.name %></td>
      <td><%= u.totalprofit %></td></tr>
    <% end %>
  </table>
 </div>


 <div class="onlinenow">
    <div id="tradersnow">
      TRADERS ONLINE
  <div>
        <%= User.online_now.count %>
   </div>
 </div>
 </div> <!--onlinenow-->
</div> <!--lead and online-->
</div> <!--covcontainer-->

</div> <!--lcontainer-->


<div class="appst">
  TRY THE APP
  <div class="gm google"><i class="fab fa-google-play"></i>Google Play</div>
  <div class="gm ios"><i class="fab fa-app-store-ios"></i>iOS Store</div>
  <div class="gm discord"><i class="fab fa-discord"></i>Discord</div>
</div>


<div class="acontainer">

<div class="reffooter">
  <div class="reffoot1">
    <div class="reffoot1le">
      <ul class="footone">
        <li><h2>Languages</h2></li>
        <li><%= link_to "English"%></li>
        <li><%= link_to "French"%></li>
        <li><%= link_to "Spanish"%></li>
        <li><%= link_to "German"%></li>
        <li><%= link_to "Italian"%></li>
        <li><%= link_to "Portuguese"%></li>
      </ul>
    </div>
    <div class="reffoot1ri">
      <ul class="foottwo">
        <li><h2>Other Links</h2></li>
        <li><%= link_to "Companies"%></li>
        <li><%= link_to "News"%></li>
        <li><%= link_to "Leaderboard"%></li>
        <li><%= link_to "Why Sign Up"%></li>
        <li><%= link_to "Go Premium"%></li>
      </ul>
    </div>
  </div>
  <div class="reffoot2">
    <div class="reffoot2le">
      <ul class="footthree">
        <li><h2>Get To Know Us</h2></li>
        <li><%= link_to "About"%></li>
        <li><%= link_to "Facebook"%></li>
        <li><%= link_to "Twitter"%></li>
        <li><%= link_to "Instagram"%></li>
        <li><%= link_to "Contact Us"%></li>
      </ul>
    </div>
    <div class="reffoot2ri">
      <ul class="footfour">
        <li><h2>Helpful Resources</h2></li>
        <li><%= link_to "TBA"%></li>
        <li><%= link_to "TBA"%></li>
        <li><%= link_to "TBA"%></li>
        <li><%= link_to "TBA"%></li>
      </ul>
    </div>
  </div>
</div>

</div><!--acontainer-->
<script>
  const input = document.getElementById("containTxt");
  console.log("works");
  input.addEventListener("keyup", function(event) {
     if (this.value == '' || this.value == this.defaultValue) {
       return
   } else if (event.keyCode === 13) {
       event.preventDefault();
       url = "https://sheltered-journey-51023.herokuapp.com/usearch/" + input.value
       //url = "http://localhost:3000/usearch/" + input.value
       window.location = url;
      }
    });
</script>

app/views/staticpages/home.js.erb
// 
// CompanyPoller.poll();

app/views/staticpages/index.js.erb
alert("it works!");

app/views/staticpages/leaderboard.html.erb
<div class="homenav">
<div class="offset">
  <div class="centerset">
    <div class="topset">
  <div class="logo">
      <%= link_to "SportFolio", root_path, id: "homelogo" %>
  </div>
  <div class="searchhold">
     <div class="inputsm">
       <div class="refSearch"><i class="fa fa-search"></i></div>
       <input type="text" id="inputTxt" placeholder="Search">
     </div>
  </div>
  <div class="signup">
          <% if user_signed_in? %>
          <%= link_to "Edit profile", edit_user_registration_path %> |
          <%= link_to "Logout", users_sign_out_path, method: :delete  %>
          <% else %>
          <i class="fab fa-facebook-f"></i>
           <i class="fas fa-user"></i><%= link_to "Sign up", new_user_registration_path  %> |
           <%= link_to "Login", new_user_session_path  %>
          <% end %>
  </div>


  </div> <!-- topset -->
  <div class="bottomset">

    <ul class="setlist">
      <li><%= link_to "COMPANIES", companies_path%></li>
      <li>NEWS</li>
      <li><%= link_to "LEADERBOARD", leaderboard_path%></li>
      <% if user_signed_in? %>
      <li><%= link_to "PROFILE", user_path(current_user)%></li>
      <li>GO PREMIUM</li>

      <% else %>
      <li><%= link_to "HOME", root_path %></li>
      <li>GO PREMIUM</li>

      <% end %>
    </ul>
  </div>
  </div>  <!-- centerset -->


</div>


</div>

<div class="leaderboardlarge">
  <h2 class="leaderboardtitle">Leaderboard <span class="usertotalsp">(<%= @total %>)</span></h2>
  <%= will_paginate @users %>
<table>
  <tr>
    <th>RANK</th>
    <th>TRADER</th>
    <th></th>
    <th>UNITS</th>
    <th>TRADES</th>
  </tr>

  <% @users.each_with_index do |u, index| %>
  <tr class="trlist">
    <td><%= @users.offset + index + 1 %></td>
    <td><span class="ilarge"><i class="fas fa-medal" style="color:#FFD700;"></i></span><%= link_to u.name, user_path(u) %></td>
    <td><%= image_tag u.avatar.url(:thumb) %><span class="leaderboardrank"><%= u.toprank %></span></td>
    <td><%= u.wallet %></td>
    <td><%= u.trades.count %></td></tr>

  <% end %>






</table>
</div>
<script>
  const userTotal = document.getElementsByClassName("usertotalsp")[0].innerText;
  function top1() {
    n = userTotal / 99
    num = Math.ceil(n)
    $.ajax({
         url: "http://localhost:3000/staticpages/rank",
         data: {topnum: num, topstr: "Top 1%"  },
         success: function(response){
           console.log("had success")
         }
       })
  }
  function top25() {
    num2 = userTotal / 4
    $.ajax({
         url: "http://localhost:3000/staticpages/rank",
         data: {topnum: num2, topstr: "Top 25%"  },
         success: function(response){
           console.log("had success")
           // top1()
           }
         })
  }
  function top50() {
    num3 = userTotal / 2
    $.ajax({
         url: "http://localhost:3000/staticpages/rank",
         data: {topnum: num3, topstr: "Top 50%"},
         success: function(response){
           console.log("had success")
           // top25();
           }
         })
  }

  top50();
  top25();
  top1();

</script>

app/views/staticpages/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/staticpages/news.html.erb

<div class="homenav">
<div class="offset">
  <div class="centerset">
    <div class="topset">
  <div class="logo">
      <%= link_to "SportFolio", root_path, id: "homelogo" %>
  </div>
  <div class="searchhold">
     <div class="inputsm">
       <div class="refSearch"><i class="fa fa-search"></i></div>
       <input type="text" id="inputTxt" placeholder="Search">
     </div>
  </div>
  <div class="signup">
          <% if user_signed_in? %>
          <%= link_to "Edit profile", edit_user_registration_path %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
          <% else %>
          <i class="fab fa-facebook-f"></i>
           <i class="fas fa-user"></i><%= link_to "Sign up", new_user_registration_path  %> |
           <%= link_to "Login", new_user_session_path  %>
          <% end %>
  </div>


  </div> <!-- topset -->
  <div class="bottomset">

    <ul class="setlist">
      <li><%= link_to "COMPANIES", companies_path%></li>
      <li>NEWS</li>
      <li><%= link_to "LEADERBOARD", leaderboard_path%></li>
      <% if user_signed_in? %>
      <li><%= link_to "PROFILE", user_path(current_user)%></li>
      <li>GO PREMIUM</li>

      <% else %>
      <li><%= link_to "HOME", root_path %></li>
      <li>GO PREMIUM</li>
      <% end %>
    </ul>
  </div>
  </div>  <!-- centerset -->


</div>


</div>   <!-- homenav -->



<div class="newswrap">
<%= image_tag "#{@news.imageurl}", class: "nimglarge" %>
<div class="nwstitle"><%= @news.title %><br>
  <%= @news.publishedon %>
</div>
<div class="nwsbody">
<%= @news.content %><br>
<%= @news.long%>
</div>


</div>

app/views/staticpages/tour.html.erb
<h1>Staticpages#tour</h1>
<p>Find me in app/views/staticpages/tour.html.erb</p>