config/routes.rb
Rails.application.routes.draw do



 get '/users/trade' => 'users#trade'



  get 'trades/findcompany', to: "trades#findcompany"
  get 'users/newtrade', to: "users#newtrade"
  resources :examples
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { sessions: "devise/sessions", omniauth_callbacks: 'omniauth_callbacks' }
  get 'auth/:provider/callback', to: 'devise/sessions#create'


  get '/', to: "staticpages#home"
  get '/leaderboard', to: "staticpages#leaderboard"
  post 'search' => 'users#search'

  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  root 'devise/sessions#new'
  end


  resources :companies do
    collection do
      get 'events'
    end
  end

  # post 'companies/publish', to: "companies#pub"
  #
  # get 'companies/subscribe', to: "companies#sub"



  get 'staticpages/help'

  get 'staticpages/tour'
  get 'staticpages/about'
  get 'staticpages/rank'

  get 'static/pages'
  get 'users/preview'
  get 'users/revise'
  get 'staticpages/news/:id', to: "staticpages#news"
  get 'usearch/:name', to: "staticpages#usearch"
  # get '/sectors/:id', to: "sectors#show"
  resources :sectors

  resources :users do
    resources :trades
  end





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
require 'rest-client'
require 'json'
require 'nokogiri'
require 'open-uri'
# Refresh the cached action_methods when a new action_method is added.
class Company < ApplicationRecord
 has_and_belongs_to_many :trades

 def self.search(search)
   if search
     where('otherdata ilike ? OR ticker ilike ?', "%#{search}%", "#{search}")
   else
     self.where(nil)
   end
 end

 def chngepercntges

    RestClient.get("https://api.iextrading.com/1.0/stock/#{self.ticker}/quote") { |response, request, result, &block|
           case response.code
           when 200
             data = JSON.parse(response.body)
             self.changepercent = data["changePercent"]
           when 404
             self.changepercent = 0
            else
             self.changepercent = 0
            end
  }
 end
 def crrntprices

     RestClient.get("https://api.iextrading.com/1.0/tops/last?symbols=#{self.ticker}") { |response, request, result, &block|
            case response.code
            when 200                #revise this to an if else statement.  also maybe put all attribute updates in a single method
              data = JSON.parse(response.body)
              self.currentprice = data[0]["price"].to_f
            when 404
              self.currentprice = 0
             else
              self.currentprice = 0
             end
             self.save
   }
 end
 def self.updatecrrnt
  Company.all.each {|c| c.crrntprices}
 end
 def volume

      RestClient.get("https://api.iextrading.com/1.0/stock/#{self.ticker}/quote") { |response, request, result, &block|
         case response.code
          when 200
               data = JSON.parse(response.body)
               self.volume = data["latestVolume"]
           when 404
               self.volume = 0
              else
               self.volume = 0
          end
    }
  end

  def updatechanges
    @test = Company.order('changepercent DESC').limit(20)
    @test.each do |c|
    # @test.order('changepercent DESC') do |c|
    c.chngepercntges
    c.save
    puts c.name
    end
  end

  def updatecurrentandvol
   @test = Company.all
   @test.find_each(batch_size: 10) do |c|
   # @test.order('changepercent DESC') do |c|
   c.crrntprices
   c.volume
   c.save
   puts c.ticker
   end
  end


 

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  include ActionController::Live
  # rescue_from ActionView::Template::Error, with: :handle_timeout
  # before_action :authenticate_user!, only: [:show]
  before_action :set_company, only: [:edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.first(10)   #will show by Company.order('latestvolume DESC').limit(25)
    @test = Company.search(params[:search]).paginate(page: params[:page], per_page: 30)
    @bigcomp = @test.order('changepercent DESC').limit(20)
    respond_to do |format|
      format.js
      format.html
    end
  end
  # GET /companies/1
  # GET /companies/1.json
  def show

  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
    render layout: false
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.create!(company_params)
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    @company = Company.update(company_params)
    # $redis.publish('companies.update', @company.to_json)
    # render :action => 'show'
  end
  #
  def events
    response.headers['Content-Type'] = "text/event-stream"
    redis = Redis.new
    redis.subscribe('companies.update') do |on|
      on.message do |event, data|
        response.stream.write('data: #{data}\n\n')
      end
    end
  end

  #   def pub
  #       $redis.publish 'chat_event', params[:chat_data].to_json
  #       render json: {}, status: 200
  #   end
  #
  # def sub
  #       response.headers["Content-Type"] = "text/event-stream"
  #
  #       redis = Redis.new
  #       redis.subscribe(['chat_event', 'heartbeat']) do |on|
  #           on.message do |event, data|
  #               response.stream.write "event: #{event}\ndata: #{data}\n\n"
  #           end
  #       end
  #   rescue IOError
  #       logger.info "Stream Closed"
  #   ensure
  #       redis.quit
  #       response.stream.close
  #   end
  #

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  protected

  # def handle_timeout(exception)
  #   count = 0
  #   begin if count < 10
  #     retry
  #
  #
  #
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:change, :changepercent, :name, :ticker)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_companies.html.erb




<div class="flickr_pagination">
  <div class="page_info">
    <%= page_entries_info @test %>
  </div>
  <%= will_paginate @test, :container => false %>
  <table id="myTable">
    <tr>
      <th>Symbol</th>
      <th>Name</th>
    </tr>
    <% @test.each do |c| %>
    <tr>
      <td class="tick"><%= link_to c.ticker, "https://www.nasdaq.com/symbol/#{c.ticker}" %></td>
      <td class="ctitle"><%= c.otherdata %></td>
    </tr>
  <% end %>
  </table>
</div>

app/views/companies/_company.html.erb
<nobr>
<% @bigcomp.each do |c| %>
  <span class="spn">
   <!-- <%= c.name %> -->
   <%= content_tag(:span, "#{c.ticker}  ", class: "ticker") %>&nbsp&nbsp&nbsp
   <%= content_tag(:span, "  #{c.changepercent * 100}%", class: "change-price") %>
   <%= content_tag(:div, "#{c.currentprice}" , class: "currentprice")%>
   <span class="vole">Volume:</span>
   <%= content_tag(:span, "#{c.volume}" , class: "volume")%>

 </span>
<% end %>
</nobr>

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= form.text_field :change %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<head>

 <h1>Editing Company</h1>
</head>
<body>
<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>
</body>

app/views/companies/index.html.erb
   <!-- for devise  move to app layout -->
   <div class="homenav">
   <div class="offset">
   <div class="centerset">
     <div class="topset">
     <div class="logo">
         <%= link_to "SportFolio", root_path, id: "homelogo" %>
     </div>
     <div class="searchhold">
        <div class="inputsm">
          <div class="refSearch"><i class="fa fa-search"></i></div>
          <input type="text" id="inputTxt" placeholder="Search">
        </div>
     </div>
     <div class="signup">
             <% if user_signed_in? %>
             <%= link_to "Edit profile", edit_user_registration_path %> |
             <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
             <% else %>
             <i class="fab fa-facebook-f"></i>
              <i class="fas fa-user"></i><%= link_to "Sign up", new_user_registration_path  %> |
              <%= link_to "Login", new_user_session_path  %>
             <% end %>
     </div>


     </div> <!-- topset -->
     <div class="bottomset">

       <ul class="setlist">
         <li><%= link_to "COMPANIES", companies_path%></li>
         <li>NEWS</li>
         <li><%= link_to "LEADERBOARD", leaderboard_path%></li>
         <% if user_signed_in? %>
         <li><%= link_to "PROFILE", user_path(current_user)%></li>
         <li>GO PREMIUM</li>

         <% else %>
         <li><%= link_to "HOME", root_path %></li>
         <li>GO PREMIUM</li>

         <% end %>
       </ul>
     </div>
     </div>  <!-- centerset -->


   </div>


   </div>   <!-- homenav -->

<div class="compIndex">


<%= form_tag companies_path, :method => 'get', id: "companies_search" do %>

  <div class="csearch">
    <div class="csearchicon"><i class="fas fa-search"></i></div>
  <%= text_field_tag :search, params[:search], id: "isearch", placeholder: "Type keyword and press enter"  %>

 </div>
<% end %>




<div id="companies"><%= render "companies" %></div>

</div>

app/views/companies/index.js.erb
//every three seconds this happens
$("#companies").html("<%= escape_javascript(render("companies")) %>");

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>